name: Rebase Upstream

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          # Must be larger than the number of commits that need to be rebased.
          fetch-depth: 10

      - name: Rebase
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com";
          git config --local user.name  "GitHub Actions";

          git remote add upstream https://github.com/revk/ESP32-Faikin
          git fetch upstream main
          git rebase upstream/main

          ORIGIN_URL=$(git remote get-url origin);
          git push "${ORIGIN_URL/https:\/\//https:\/\/$GITHUB_TOKEN@}" main --force
